// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: TempoView

#include "../ui.h"

lv_obj_t *uic_nbrouge;
lv_obj_t *uic_nbblanc;
lv_obj_t *uic_nbbleu;
lv_obj_t *uic_panelrouge;
lv_obj_t *uic_panelbleu;
lv_obj_t *uic_panelblanc;
lv_obj_t *uic_demain;
lv_obj_t *uic_paneldemain;
lv_obj_t *uic_aujourdhui;
lv_obj_t *uic_panelajourdhui;
lv_obj_t *uic_barconso;
lv_obj_t *uic_conso;
lv_obj_t *uic_periode;
lv_obj_t *uic_panelconso;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_panelconso = NULL;lv_obj_t *ui_periode = NULL;lv_obj_t *ui_conso = NULL;lv_obj_t *ui_barconso = NULL;lv_obj_t *ui_panelajourdhui = NULL;lv_obj_t *ui_aujourdhui = NULL;lv_obj_t *ui_paneldemain = NULL;lv_obj_t *ui_demain = NULL;lv_obj_t *ui_panelblanc = NULL;lv_obj_t *ui_panelbleu = NULL;lv_obj_t *ui_panelrouge = NULL;lv_obj_t *ui_nbbleu = NULL;lv_obj_t *ui_nbblanc = NULL;lv_obj_t *ui_nbrouge = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xE5BF8D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelconso = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_panelconso, 310);
lv_obj_set_height( ui_panelconso, 58);
lv_obj_set_x( ui_panelconso, 0 );
lv_obj_set_y( ui_panelconso, -45 );
lv_obj_set_align( ui_panelconso, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_panelconso, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelconso, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelconso, lv_color_hex(0xE5BF8D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelconso, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panelconso, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panelconso, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panelconso, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panelconso, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_panelconso, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_panelconso, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_panelconso, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_panelconso, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_periode = lv_label_create(ui_panelconso);
lv_obj_set_width( ui_periode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_periode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_periode, -131 );
lv_obj_set_y( ui_periode, 12 );
lv_obj_set_align( ui_periode, LV_ALIGN_CENTER );
lv_label_set_text(ui_periode,"HP");
lv_obj_set_style_text_color(ui_periode, lv_color_hex(0x058703), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_periode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_conso = lv_label_create(ui_panelconso);
lv_obj_set_width( ui_conso, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_conso, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_conso, 0 );
lv_obj_set_y( ui_conso, -8 );
lv_obj_set_align( ui_conso, LV_ALIGN_CENTER );
lv_label_set_text(ui_conso,"eee");
lv_obj_set_style_text_font(ui_conso, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_barconso = lv_bar_create(ui_panelconso);
lv_obj_set_width( ui_barconso, 245);
lv_obj_set_height( ui_barconso, 6);
lv_obj_set_x( ui_barconso, 14 );
lv_obj_set_y( ui_barconso, 13 );
lv_obj_set_align( ui_barconso, LV_ALIGN_CENTER );

ui_panelajourdhui = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_panelajourdhui, 310);
lv_obj_set_height( ui_panelajourdhui, 32);
lv_obj_set_x( ui_panelajourdhui, -1 );
lv_obj_set_y( ui_panelajourdhui, 9 );
lv_obj_set_align( ui_panelajourdhui, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_panelajourdhui, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panelajourdhui, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panelajourdhui, lv_color_hex(0x386A77), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelajourdhui, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panelajourdhui, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panelajourdhui, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_panelajourdhui, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_panelajourdhui, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_panelajourdhui, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_panelajourdhui, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aujourdhui = lv_label_create(ui_panelajourdhui);
lv_obj_set_width( ui_aujourdhui, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aujourdhui, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aujourdhui, LV_ALIGN_CENTER );
lv_label_set_text(ui_aujourdhui,"aujourd'hui : XXX");

ui_paneldemain = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_paneldemain, 310);
lv_obj_set_height( ui_paneldemain, 32);
lv_obj_set_x( ui_paneldemain, 0 );
lv_obj_set_y( ui_paneldemain, 52 );
lv_obj_set_align( ui_paneldemain, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_paneldemain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_paneldemain, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_paneldemain, lv_color_hex(0xC8471A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_paneldemain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_paneldemain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_paneldemain, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_paneldemain, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_paneldemain, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_paneldemain, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_paneldemain, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_demain = lv_label_create(ui_paneldemain);
lv_obj_set_width( ui_demain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_demain, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_demain, LV_ALIGN_CENTER );
lv_label_set_text(ui_demain,"demain : XXX");

ui_panelblanc = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_panelblanc, 15);
lv_obj_set_height( ui_panelblanc, 15);
lv_obj_set_x( ui_panelblanc, 0 );
lv_obj_set_y( ui_panelblanc, 66 );
lv_obj_set_align( ui_panelblanc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelblanc, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_panelblanc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelblanc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelblanc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panelblanc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panelblanc, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_panelblanc, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_panelblanc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_panelblanc, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_panelblanc, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelbleu = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_panelbleu, 15);
lv_obj_set_height( ui_panelbleu, 15);
lv_obj_set_x( ui_panelbleu, -80 );
lv_obj_set_y( ui_panelbleu, 66 );
lv_obj_set_align( ui_panelbleu, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelbleu, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_panelbleu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelbleu, lv_color_hex(0x386A77), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelbleu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panelbleu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panelbleu, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_panelbleu, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_panelbleu, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_panelbleu, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_panelbleu, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panelrouge = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_panelrouge, 15);
lv_obj_set_height( ui_panelrouge, 15);
lv_obj_set_x( ui_panelrouge, 80 );
lv_obj_set_y( ui_panelrouge, 66 );
lv_obj_set_align( ui_panelrouge, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panelrouge, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_panelrouge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panelrouge, lv_color_hex(0xC8471A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panelrouge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_panelrouge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_panelrouge, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_panelrouge, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_panelrouge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_panelrouge, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_panelrouge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_nbbleu = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_nbbleu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nbbleu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nbbleu, -73 );
lv_obj_set_y( ui_nbbleu, 65 );
lv_obj_set_align( ui_nbbleu, LV_ALIGN_CENTER );
lv_label_set_text(ui_nbbleu,"");
lv_obj_add_flag( ui_nbbleu, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_nbblanc = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_nbblanc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nbblanc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nbblanc, 25 );
lv_obj_set_y( ui_nbblanc, 65 );
lv_obj_set_align( ui_nbblanc, LV_ALIGN_CENTER );
lv_label_set_text(ui_nbblanc,"");
lv_obj_add_flag( ui_nbblanc, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_nbrouge = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_nbrouge, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nbrouge, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nbrouge, 104 );
lv_obj_set_y( ui_nbrouge, 65 );
lv_obj_set_align( ui_nbrouge, LV_ALIGN_CENTER );
lv_label_set_text(ui_nbrouge,"");
lv_obj_add_flag( ui_nbrouge, LV_OBJ_FLAG_HIDDEN );   /// Flags

uic_panelconso = ui_panelconso;
uic_periode = ui_periode;
uic_conso = ui_conso;
uic_barconso = ui_barconso;
uic_panelajourdhui = ui_panelajourdhui;
uic_aujourdhui = ui_aujourdhui;
uic_paneldemain = ui_paneldemain;
uic_demain = ui_demain;
uic_panelblanc = ui_panelblanc;
uic_panelbleu = ui_panelbleu;
uic_panelrouge = ui_panelrouge;
uic_nbbleu = ui_nbbleu;
uic_nbblanc = ui_nbblanc;
uic_nbrouge = ui_nbrouge;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_panelconso= NULL;
ui_panelconso= NULL;
uic_periode= NULL;
ui_periode= NULL;
uic_conso= NULL;
ui_conso= NULL;
uic_barconso= NULL;
ui_barconso= NULL;
uic_panelajourdhui= NULL;
ui_panelajourdhui= NULL;
uic_aujourdhui= NULL;
ui_aujourdhui= NULL;
uic_paneldemain= NULL;
ui_paneldemain= NULL;
uic_demain= NULL;
ui_demain= NULL;
uic_panelblanc= NULL;
ui_panelblanc= NULL;
uic_panelbleu= NULL;
ui_panelbleu= NULL;
uic_panelrouge= NULL;
ui_panelrouge= NULL;
uic_nbbleu= NULL;
ui_nbbleu= NULL;
uic_nbblanc= NULL;
ui_nbblanc= NULL;
uic_nbrouge= NULL;
ui_nbrouge= NULL;

}
