// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: TempoView

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_panelconso;
extern lv_obj_t *ui_periode;
extern lv_obj_t *ui_conso;
extern lv_obj_t *ui_barconso;
extern lv_obj_t *ui_panelajourdhui;
extern lv_obj_t *ui_aujourdhui;
extern lv_obj_t *ui_paneldemain;
extern lv_obj_t *ui_demain;
extern lv_obj_t *ui_panelblanc;
extern lv_obj_t *ui_panelbleu;
extern lv_obj_t *ui_panelrouge;
extern lv_obj_t *ui_nbbleu;
extern lv_obj_t *ui_nbblanc;
extern lv_obj_t *ui_nbrouge;
// CUSTOM VARIABLES
extern lv_obj_t *uic_panelconso;
extern lv_obj_t *uic_periode;
extern lv_obj_t *uic_conso;
extern lv_obj_t *uic_barconso;
extern lv_obj_t *uic_panelajourdhui;
extern lv_obj_t *uic_aujourdhui;
extern lv_obj_t *uic_paneldemain;
extern lv_obj_t *uic_demain;
extern lv_obj_t *uic_panelblanc;
extern lv_obj_t *uic_panelbleu;
extern lv_obj_t *uic_panelrouge;
extern lv_obj_t *uic_nbbleu;
extern lv_obj_t *uic_nbblanc;
extern lv_obj_t *uic_nbrouge;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

